# Generated by Django 4.2.13 on 2024-06-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticiero', '0003_noticia_imagen_alter_noticia_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='noticias_imagenes/'),
        ),
    ]
