# Generated by Django 4.2.13 on 2024-06-30 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticiero', '0008_carrito_itemcarrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrito',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='subscripcion',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='ItemCarrito',
        ),
    ]
