# Generated by Django 4.2.13 on 2024-06-30 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticiero', '0010_noticia_creador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='creador',
        ),
    ]
